"""The site's springs (parts/springs.py), from Motion's own spring().

The client asked on 26 Sep 2026 that motion.dev's tools be used wherever
they fit. Things that travel on the site (a rail scaling in, an arrow's head
sliding, a line drawing itself, a photo growing out of its thumbnail) move on
Motion's springs, bounce 0, generated by tools/motion_springs.mjs; colour,
opacity and anything that moves the layout keep their curves. The figures
redrawn from numerical models carry the same spring in their engine.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "site"))

from parts import gallery, springs, theme  # noqa: E402

TOKENS = {"quick": 120, "fast": 160, "mid": 240, "draw": 360, "slow": 420}


def test_each_travel_token_has_its_spring():
    assert {k: v[0] for k, v in springs.SPRINGS.items()} == TOKENS
    for name, (visual, settle, easing) in springs.SPRINGS.items():
        # the spring settles after it arrives, and never overshoots (bounce 0)
        assert visual < settle <= 2.2 * visual
        stops = [float(v) for v in re.fullmatch(r"linear\((.*)\)", easing).group(1).split(",")]
        assert stops[0] == 0 and stops[-1] == 1
        assert all(b >= a for a, b in zip(stops, stops[1:])) and max(stops) <= 1
        assert f"--spring-{name}:{settle}ms {easing};" in theme.CSS
    assert re.fullmatch(r"\d+\.\d+\.\d+", springs.MOTION)


def test_travel_moves_on_springs_and_colour_and_layout_keep_their_curves():
    site = os.path.join(ROOT, "site")
    files = [os.path.join(site, "build.py")] + [
        os.path.join(site, "parts", n) for n in os.listdir(os.path.join(site, "parts"))
        if n.endswith(".py")]
    travel = re.compile(r"\b(transform|stroke-dashoffset|clip-path) var\(--t-\w+\) var\(--ease\)")
    for f in files:
        with open(f, encoding="utf-8") as fh:
            text = fh.read()
        assert not travel.search(text), f
    assert ".main{transition:margin-left var(--t-mid) var(--ease)}" in theme.CSS
    assert "var(--spring-mid)" in theme.CSS


def test_the_gallery_photo_arrives_on_a_spring_where_the_browser_can():
    js = gallery.JS
    assert "var SPRING={}" not in js and '"draw":[700,"linear(0,' in js
    assert "CSS.supports('transition-timing-function','linear(0, 1)')" in js
    assert "morph(t,rect(media),'draw',340)" in js


def test_the_figures_carry_motions_spring():
    with open(os.path.join(ROOT, "tools", "numfig", "engine.js"), encoding="utf-8") as fh:
        engine = fh.read()
    assert "function settle(t0, visual, bounce = 0)" in engine
    assert "Copyright (c) 2024 Motion (https://motion.dev) B.V." in engine
